## Adminer ##
server {
    listen 80;
    server_name adminer.local;
    charset utf-8;
    client_max_body_size 32m;
    error_log /dev/stdout debug;
    location / {
        proxy_set_header Host $host;
        proxy_pass http://adminer:8080;
    }
}

## SONARY ##
server {
    listen 80;
    server_name sonary.test;
    charset utf-8;
    client_max_body_size 32m;
    error_log /dev/stdout debug;

    # Backend API
    location /api/ {
        proxy_set_header Host $host;
        proxy_pass http://sonary-backend:8080;
        # additional headers
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Backend Websocket
    location /ws {
        proxy_set_header Host $host;
        proxy_pass http://sonary-backend:8080;
        # enable WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # additional headers
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # avoid closing connection by timeout
        proxy_read_timeout 7d;
        proxy_send_timeout 7d;
    }

    # Vite Frontend
    location / {
        proxy_set_header Host $host;
        proxy_pass http://sonary-frontend:3000;
    }
}

# HMR Websocket for Vite
server {
    listen 3104;
    location / {
        proxy_pass http://sonary-frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        # avoid closing connection by timeout
        proxy_read_timeout 7d;
        proxy_send_timeout 7d;
  }
}
