name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run Tests
        run: make test
